### ISSUE TITLE
How to get connect information from runpodctl ?

### ISSUE THREAD

**Issue by thecloudco** [runpod/runpodctl#30]
After creating a pod with runpodctl, how can I get the same connection information that I get on the console to access the pod. I am talking about the ssh connection info (e.g: ssh 11111111111111-11111115@ssh.runpod.io -i ~/.ssh/id_ed1111111)

Right now I have to login to the console to get this information. What is the preffered way to get this from the CLI ?

**Comment by denstepa** [comment]
+1 here. It is very annoying that over CLI it's not possible to either execute remote command or get details about SSH. For us it makes use of CLI rather useless

**Comment by jojje** [comment]
I have the same issue, and am working on implementing this.
My plan is to solve this in two steps.
1. Add an option to `create pod` that allows for starting the SSH server, since it isn't by default. Can't do SSH login without the sshd server running, so this is a pre-req.
2. Output the SSH connect string, exactly like in the web console.

No. 1 is easy, as I already have a patch for it that I'll push shortly (and reference this ticket).

As for no 2, I'm not sure where best to add this. As part of the `ssh` sub-command seems most logical though, so I think I'll start there, but suggestions are welcome.
